In [12]:
import pandas as pd
import numpy as np

ufos = pd.read_csv('./data/ufos.csv')
ufos = pd.DataFrame({'Seconds': ufos['duration (seconds)'], 'Country': ufos['country'],'Latitude': ufos['latitude'],'Longitude': ufos['longitude']})
ufos.dropna(inplace=True)

ufos = ufos[(ufos['Seconds'] >= 1) & (ufos['Seconds'] <= 60)]
ufos.head()

    Seconds Country   Latitude   Longitude
2      20.0      gb  53.200000   -2.916667
3      20.0      us  28.978333  -96.645833
14     30.0      us  35.823889  -80.253611
23     60.0      us  45.582778 -122.352222
24      3.0      gb  51.783333   -0.783333

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

ufos['Country'] = label_encoder.fit_transform(ufos['Country'])

ufos.head()

    Seconds  Country   Latitude   Longitude
2      20.0        3  53.200000   -2.916667
3      20.0        4  28.978333  -96.645833
14     30.0        4  35.823889  -80.253611
23     60.0        4  45.582778 -122.352222
24      3.0        3  51.783333   -0.783333

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

selected_features = [
    'Seconds',
    'Latitude',
    'Longitude'
]

feature_data = ufos[selected_features] 
label_data = ufos['Country']

x_train,x_test,y_train,y_test = train_test_split(
    feature_data,
    label_data,
    test_size=0.2
) 
model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)


print(classification_report(y_test, y_pred))
print('Predicted labels: ', y_pred)
print('Accuracy: ', accuracy_score(y_test, y_pred))

print('Confusion Matrix', confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.81      0.11      0.20       256
           2       1.00      1.00      1.00         7
           3       1.00      1.00      1.00       159
           4       0.95      1.00      0.98      4716

    accuracy                           0.95      5173
   macro avg       0.95      0.82      0.83      5173
weighted avg       0.95      0.95      0.94      5173

Predicted labels:  [4 3 4 ... 4 4 4]
Accuracy:  0.9547651266189832
Confusion Matrix [[  35    0    0    0    0]
 [   0   29    0    0  227]
 [   0    0    7    0    0]
 [   0    0    0  159    0]
 [   0    7    0    0 4709]]

/Users/don/Desktop/machine-learning/ml-for-beginners/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
import pickle
model_filename = 'ufo-model.pkl'
pickle.dump(model, open(model_filename,'wb'))

model = pickle.load(open('ufo-model.pkl','rb'))
print(model.predict([[50,44,-12]]))

[3]

/Users/don/Desktop/machine-learning/ml-for-beginners/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(